// Generates every app icon / splash asset from assets/logo.svg (the fixed brand mark).
// Usage: npm run assets
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = (name) => path.join(root, 'assets', 'images', name);
const VIEWBOX = 140;

const logo = await readFile(path.join(root, 'assets', 'logo.svg'), 'utf8');

/** Logo without its white background square. */
const transparent = logo.replace(/<rect[^>]*\/>\s*/, '');

/** Every stroke/fill in one colour (Android monochrome + notification icon masks). */
const mono = (color) =>
  transparent
    .replace(/fill="#FFFFFF"/g, 'fill="none"')
    .replace(/stroke="#[0-9A-Fa-f]{6}"/g, `stroke="${color}"`);

/** Places the 140-unit artwork on a larger canvas so it fits a platform safe zone. */
const padded = (svg, canvasUnits) => {
  const offset = (canvasUnits - VIEWBOX) / 2;
  return svg
    .replace('viewBox="0 0 140 140"', `viewBox="${-offset} ${-offset} ${canvasUnits} ${canvasUnits}"`);
};

async function render(svg, size, file, { flatten = false } = {}) {
  const density = Math.ceil((size / VIEWBOX) * 72 * 2);
  let img = sharp(Buffer.from(svg), { density }).resize(size, size);
  if (flatten) img = img.flatten({ background: '#FFFFFF' });
  await img.png({ compressionLevel: 9 }).toFile(out(file));
  console.log(`✓ ${file} (${size}×${size})`);
}

// iOS / store icon: opaque white square, full mark.
await render(logo, 1024, 'icon.png', { flatten: true });
// Android adaptive icon: the circular safe zone is 66/108 of the canvas.
// The shield's corners sit ~61 units from the centre → canvas of ~210 units keeps them inside.
await render(padded(transparent, 210), 1024, 'android-icon-foreground.png');
await render(padded(mono('#000000'), 210), 1024, 'android-icon-monochrome.png');
// Splash: mark on transparent, the plugin paints the white background.
await render(transparent, 1024, 'splash-icon.png');
// Web favicon.
await render(logo, 48, 'favicon.png', { flatten: true });
// Android notification icon: all-white silhouette with transparency (96×96).
await render(padded(mono('#FFFFFF'), 150), 96, 'notification-icon.png');

await writeFile(out('.generated'), 'Generated by scripts/generate-assets.mjs from assets/logo.svg\n');
